Added Note About General Navigability
UCSantaBarbara/webguide pull request #191
Opened 2017-01-23 17:20 UTC by loganfranken

Fixes #160

2017-01-31 16:49 UTC, loganfranken commented
Hey there! Anything needed from me to merge this?

2017-02-06 16:20 UTC, loganfranken commented
Good morning! Need anything from me to merge this?

2017-02-06 17:04 UTC, garster requested changes

2017-02-06 17:04 UTC, garster commented on web-accessibility.md
> +website using techniques such as labeling the current section and using
Should this be "within the structure of **the** website"?

2017-02-07 17:23 UTC, loganfranken commented
Nice catch! Updated!

2017-02-08 15:55 UTC, merged