Updated Checklist to Reflect New Content
UCSantaBarbara/webguide pull request #196
Opened 2017-02-13 17:51 UTC by loganfranken

Fixes #153

2017-02-13 23:57 UTC, garster requested changes

2017-02-13 23:57 UTC, garster commented on checklist.md
> +* Don’t generate content with CSS
This curly quote might cause an encoding problem, convert to singlequote to match others.

2017-02-21 16:58 UTC, loganfranken commented on checklist.md
> +* Don’t generate content with CSS
Nice catch! Fixed!

2017-02-27 17:42 UTC, loganfranken commented
Hey there! I think should be good to merge now? (Let me know if you need anything from me!)

2017-03-02 13:58 UTC, garster approved these changes

2017-03-02 13:58 UTC, merged