Changes to the CSS page. links, wordsmithing and html code highlighting
UCSantaBarbara/webguide pull request #241
Opened 2017-07-26 03:56 UTC by garster

2017-07-26 03:56 UTC, garster commented
@loganfranken I think I got it all.

2017-07-26 05:42 UTC, loganfranken commented
Hey @garster! Thanks for your work on this!

The only thing is it looks like some of the bad practice examples got corrected to be good practice examples?

2017-07-26 13:36 UTC, garster commented
@loganfranken do you mean when I changed the `.red` color from #CC0000 to #C00? 

I changed it because both the good and bad examples had the long-form. The example was about the name of the class. I feel the rest of the content which is only there to fill out the example, good or bad, should be good form. Many times I have copied some code like this and got bad stuff.

2017-07-27 02:35 UTC, loganfranken commented
Ahh gotcha, my bad: I see you corrected it on the bad practice example that was focused on a different concept. Nevermind! Thanks for humoring me!

2017-07-27 20:00 UTC, dsaludares commented on css.md
> +CSS). Website developers may want to consider using stylesheet minifies, compilers,
Change "minifies" to "minifiers"

2017-07-27 20:04 UTC, dsaludares requested changes
Found one typo

2017-07-27 20:04 UTC, dsaludares commented on css.md
> +CSS). Website developers may want to consider using stylesheet minifies, compilers,
Change "minifies" to "minifiers"

2017-08-02 01:57 UTC, merged